package com.parlor.games.lastlight.random

import com.parlor.games.lastlight.LastLightTestFixture
import com.parlor.games.lastlight.domain.model.CardRank
import kotlin.test.Test
import kotlin.test.assertEquals

class LastLightRandomTest {
    @Test
    fun streamMatchesIndependentStandardHmacSha256Vectors() {
        // Python 3 hmac.new(str(seed).encode(),
        //   f'parlor:last-light:entropy:v1:{round}:0'.encode(), hashlib.sha256)
        // decoded as eight big-endian signed Int values; not generated by Kotlin.
        val vectors = listOf(
            Triple(71L, 1, listOf(1336331430, 1684897882, -1503307483, 893303723, -479027852, -1101862080, -1811457674, 1202631741)),
            Triple(71L, 2, listOf(1894207954, 1550573627, 1799688216, 1773980090, -555827394, 1262155333, -1886043391, -1698129339)),
            Triple(Long.MIN_VALUE, 35, listOf(880653543, 1001948231, -1679487894, 356436473, -1465996799, -1135267438, 1725936494, -775780887)),
        )
        for ((seed, round, expected) in vectors) {
            val random = LastLightRandom.forRound(seed, round)
            assertEquals(expected, List(8) { random.nextInt() })
        }
    }

    @Test
    fun versionOneOpeningDealMatchesAnIndependentBoundedDrawSimulation() {
        // Reference calculated with Python's HMAC-SHA-256 stream, rejection
        // sampling for bounded draws, and the documented Fisher-Yates order.
        val state = LastLightTestFixture().initial(count = 4, seed = 71L)
        assertEquals(listOf(4, 6, 5, 6), state.players.map { state.hostOnly.burnoutSteps.getValue(it.id) })
        assertEquals("player-3", state.hostOnly.openerPlayerId)
        assertEquals(CardRank.STAR, state.public.tableRank)
        val expected = listOf(
            listOf("CROWN", "STAR", "STAR", "MOON", "CROWN"),
            listOf("STAR", "STAR", "WILD", "MOON", "MOON"),
            listOf("STAR", "CROWN", "WILD", "STAR", "MOON"),
            listOf("MOON", "STAR", "CROWN", "MOON", "MOON"),
        )
        state.players.forEachIndexed { seat, player ->
            val hand = state.privatePerPlayer.getValue(player.id).hand
            assertEquals(expected[seat], hand.map { it.rank.name })
            val firstSlot = (seat + 1) % 4
            assertEquals(List(5) { "r1-c${firstSlot + it * 4}" }, hand.map { it.id })
        }
    }
}
