package com.parlor.games.wordimpostor.domain

import kotlinx.serialization.Serializable

@Serializable
enum class WordTopic(val id: String) {
    Food("food"),
    Series("series"),
    Movies("movies"),
    Football("football"),
    Sports("sports"),
    Anime("anime"),
    Animals("animals"),
    Countries("countries"),
    Cities("cities"),
    Games("games"),
    Technology("technology"),
    People("people")
}

data class TopicWord(val id: String, val group: String)

/** Offline IDs. Localized copy is resource-owned; topic membership is authoritative. */
object WordTopicBank {
    fun words(topic: WordTopic): List<TopicWord> = when (topic) {
        WordTopic.Food -> foodWords
        WordTopic.Series -> seriesWords
        WordTopic.Movies -> moviesWords
        WordTopic.Football -> footballWords
        WordTopic.Sports -> sportsWords
        WordTopic.Anime -> animeWords
        WordTopic.Animals -> animalsWords
        WordTopic.Countries -> countriesWords
        WordTopic.Cities -> citiesWords
        WordTopic.Games -> gamesWords
        WordTopic.Technology -> technologyWords
        WordTopic.People -> peopleWords
    }
    fun questions(topic: WordTopic): List<String> = when (topic) {
        WordTopic.Food -> foodQuestions
        WordTopic.Series -> seriesQuestions
        WordTopic.Movies -> moviesQuestions
        WordTopic.Football -> footballQuestions
        WordTopic.Sports -> sportsQuestions
        WordTopic.Anime -> animeQuestions
        WordTopic.Animals -> animalsQuestions
        WordTopic.Countries -> countriesQuestions
        WordTopic.Cities -> citiesQuestions
        WordTopic.Games -> gamesQuestions
        WordTopic.Technology -> technologyQuestions
        WordTopic.People -> peopleQuestions
    }

    private val foodWords = listOf(
        TopicWord("food_pizza", "food_0"),
        TopicWord("food_burger", "food_0"),
        TopicWord("food_pasta", "food_0"),
        TopicWord("food_sandwich", "food_0"),
        TopicWord("food_shawarma", "food_0"),
        TopicWord("food_koshari", "food_1"),
        TopicWord("food_foul", "food_1"),
        TopicWord("food_falafel", "food_1"),
        TopicWord("food_molokhia", "food_1"),
        TopicWord("food_mahshi", "food_1"),
        TopicWord("food_kunafa", "food_2"),
        TopicWord("food_basbousa", "food_2"),
        TopicWord("food_baklava", "food_2"),
        TopicWord("food_rice_pudding", "food_2"),
        TopicWord("food_umm_ali", "food_2"),
        TopicWord("food_mango", "food_3"),
        TopicWord("food_apple", "food_3"),
        TopicWord("food_banana", "food_3"),
        TopicWord("food_watermelon", "food_3"),
        TopicWord("food_strawberry", "food_3"),
    )

    private val foodQuestions = listOf(
        "food_q01",
        "food_q02",
        "food_q03",
        "food_q04",
        "food_q05",
        "food_q06",
        "food_q07",
        "food_q08",
        "food_q09",
        "food_q10",
        "food_q11",
        "food_q12",
        "food_q13",
        "food_q14",
        "food_q15",
        "food_q16",
        "food_q17",
        "food_q18",
    )

    private val seriesWords = listOf(
        TopicWord("series_breaking_bad", "series_0"),
        TopicWord("series_better_call_saul", "series_0"),
        TopicWord("series_prison_break", "series_0"),
        TopicWord("series_money_heist", "series_0"),
        TopicWord("series_sherlock", "series_0"),
        TopicWord("series_friends", "series_1"),
        TopicWord("series_the_office", "series_1"),
        TopicWord("series_brooklyn_nine_nine", "series_1"),
        TopicWord("series_modern_family", "series_1"),
        TopicWord("series_the_big_bang_theory", "series_1"),
        TopicWord("series_game_of_thrones", "series_2"),
        TopicWord("series_stranger_things", "series_2"),
        TopicWord("series_the_witcher", "series_2"),
        TopicWord("series_wednesday", "series_2"),
        TopicWord("series_dark", "series_2"),
        TopicWord("series_al_kabeer_awi", "series_3"),
        TopicWord("series_ragel_we_set_setat", "series_3"),
        TopicWord("series_al_wasiyya", "series_3"),
        TopicWord("series_el_leaba", "series_3"),
        TopicWord("series_nelly_and_sherihan", "series_3"),
    )

    private val seriesQuestions = listOf(
        "series_q01",
        "series_q02",
        "series_q03",
        "series_q04",
        "series_q05",
        "series_q06",
        "series_q07",
        "series_q08",
        "series_q09",
        "series_q10",
        "series_q11",
        "series_q12",
        "series_q13",
        "series_q14",
        "series_q15",
        "series_q16",
        "series_q17",
        "series_q18",
    )

    private val moviesWords = listOf(
        TopicWord("movies_inception", "movies_0"),
        TopicWord("movies_interstellar", "movies_0"),
        TopicWord("movies_avatar", "movies_0"),
        TopicWord("movies_jurassic_park", "movies_0"),
        TopicWord("movies_the_matrix", "movies_0"),
        TopicWord("movies_titanic", "movies_1"),
        TopicWord("movies_forrest_gump", "movies_1"),
        TopicWord("movies_the_shawshank_redemption", "movies_1"),
        TopicWord("movies_gladiator", "movies_1"),
        TopicWord("movies_the_godfather", "movies_1"),
        TopicWord("movies_toy_story", "movies_2"),
        TopicWord("movies_finding_nemo", "movies_2"),
        TopicWord("movies_the_lion_king", "movies_2"),
        TopicWord("movies_shrek", "movies_2"),
        TopicWord("movies_frozen", "movies_2"),
        TopicWord("movies_el_limby", "movies_3"),
        TopicWord("movies_asal_eswed", "movies_3"),
        TopicWord("movies_el_nazer", "movies_3"),
        TopicWord("movies_saeedi_in_the_american_university", "movies_3"),
        TopicWord("movies_teer_enta", "movies_3"),
    )

    private val moviesQuestions = listOf(
        "movies_q01",
        "movies_q02",
        "movies_q03",
        "movies_q04",
        "movies_q05",
        "movies_q06",
        "movies_q07",
        "movies_q08",
        "movies_q09",
        "movies_q10",
        "movies_q11",
        "movies_q12",
        "movies_q13",
        "movies_q14",
        "movies_q15",
        "movies_q16",
        "movies_q17",
        "movies_q18",
    )

    private val footballWords = listOf(
        TopicWord("football_mohamed_salah", "football_0"),
        TopicWord("football_lionel_messi", "football_0"),
        TopicWord("football_cristiano_ronaldo", "football_0"),
        TopicWord("football_kylian_mbappe", "football_0"),
        TopicWord("football_erling_haaland", "football_0"),
        TopicWord("football_al_ahly", "football_1"),
        TopicWord("football_zamalek", "football_1"),
        TopicWord("football_liverpool", "football_1"),
        TopicWord("football_barcelona", "football_1"),
        TopicWord("football_real_madrid", "football_1"),
        TopicWord("football_world_cup", "football_2"),
        TopicWord("football_champions_league", "football_2"),
        TopicWord("football_africa_cup_of_nations", "football_2"),
        TopicWord("football_premier_league", "football_2"),
        TopicWord("football_club_world_cup", "football_2"),
        TopicWord("football_penalty_kick", "football_3"),
        TopicWord("football_corner_kick", "football_3"),
        TopicWord("football_free_kick", "football_3"),
        TopicWord("football_throw_in", "football_3"),
        TopicWord("football_offside", "football_3"),
    )

    private val footballQuestions = listOf(
        "football_q01",
        "football_q02",
        "football_q03",
        "football_q04",
        "football_q05",
        "football_q06",
        "football_q07",
        "football_q08",
        "football_q09",
        "football_q10",
        "football_q11",
        "football_q12",
        "football_q13",
        "football_q14",
        "football_q15",
        "football_q16",
        "football_q17",
        "football_q18",
    )

    private val sportsWords = listOf(
        TopicWord("sports_basketball", "sports_0"),
        TopicWord("sports_volleyball", "sports_0"),
        TopicWord("sports_handball", "sports_0"),
        TopicWord("sports_rugby", "sports_0"),
        TopicWord("sports_hockey", "sports_0"),
        TopicWord("sports_tennis", "sports_1"),
        TopicWord("sports_squash", "sports_1"),
        TopicWord("sports_badminton", "sports_1"),
        TopicWord("sports_table_tennis", "sports_1"),
        TopicWord("sports_padel", "sports_1"),
        TopicWord("sports_swimming", "sports_2"),
        TopicWord("sports_running", "sports_2"),
        TopicWord("sports_cycling", "sports_2"),
        TopicWord("sports_rowing", "sports_2"),
        TopicWord("sports_skiing", "sports_2"),
        TopicWord("sports_boxing", "sports_3"),
        TopicWord("sports_karate", "sports_3"),
        TopicWord("sports_judo", "sports_3"),
        TopicWord("sports_taekwondo", "sports_3"),
        TopicWord("sports_wrestling", "sports_3"),
    )

    private val sportsQuestions = listOf(
        "sports_q01",
        "sports_q02",
        "sports_q03",
        "sports_q04",
        "sports_q05",
        "sports_q06",
        "sports_q07",
        "sports_q08",
        "sports_q09",
        "sports_q10",
        "sports_q11",
        "sports_q12",
        "sports_q13",
        "sports_q14",
        "sports_q15",
        "sports_q16",
        "sports_q17",
        "sports_q18",
    )

    private val animeWords = listOf(
        TopicWord("anime_naruto", "anime_0"),
        TopicWord("anime_one_piece", "anime_0"),
        TopicWord("anime_dragon_ball", "anime_0"),
        TopicWord("anime_bleach", "anime_0"),
        TopicWord("anime_hunter_x_hunter", "anime_0"),
        TopicWord("anime_attack_on_titan", "anime_1"),
        TopicWord("anime_death_note", "anime_1"),
        TopicWord("anime_demon_slayer", "anime_1"),
        TopicWord("anime_jujutsu_kaisen", "anime_1"),
        TopicWord("anime_fullmetal_alchemist", "anime_1"),
        TopicWord("anime_haikyu", "anime_2"),
        TopicWord("anime_slam_dunk", "anime_2"),
        TopicWord("anime_blue_lock", "anime_2"),
        TopicWord("anime_captain_tsubasa", "anime_2"),
        TopicWord("anime_kuroko_basketball", "anime_2"),
        TopicWord("anime_pokemon", "anime_3"),
        TopicWord("anime_digimon", "anime_3"),
        TopicWord("anime_detective_conan", "anime_3"),
        TopicWord("anime_doraemon", "anime_3"),
        TopicWord("anime_spy_x_family", "anime_3"),
    )

    private val animeQuestions = listOf(
        "anime_q01",
        "anime_q02",
        "anime_q03",
        "anime_q04",
        "anime_q05",
        "anime_q06",
        "anime_q07",
        "anime_q08",
        "anime_q09",
        "anime_q10",
        "anime_q11",
        "anime_q12",
        "anime_q13",
        "anime_q14",
        "anime_q15",
        "anime_q16",
        "anime_q17",
        "anime_q18",
    )

    private val animalsWords = listOf(
        TopicWord("animals_lion", "animals_0"),
        TopicWord("animals_tiger", "animals_0"),
        TopicWord("animals_leopard", "animals_0"),
        TopicWord("animals_cheetah", "animals_0"),
        TopicWord("animals_wolf", "animals_0"),
        TopicWord("animals_elephant", "animals_1"),
        TopicWord("animals_giraffe", "animals_1"),
        TopicWord("animals_zebra", "animals_1"),
        TopicWord("animals_rhino", "animals_1"),
        TopicWord("animals_hippo", "animals_1"),
        TopicWord("animals_cat", "animals_2"),
        TopicWord("animals_dog", "animals_2"),
        TopicWord("animals_rabbit", "animals_2"),
        TopicWord("animals_hamster", "animals_2"),
        TopicWord("animals_guinea_pig", "animals_2"),
        TopicWord("animals_dolphin", "animals_3"),
        TopicWord("animals_whale", "animals_3"),
        TopicWord("animals_shark", "animals_3"),
        TopicWord("animals_octopus", "animals_3"),
        TopicWord("animals_sea_turtle", "animals_3"),
    )

    private val animalsQuestions = listOf(
        "animals_q01",
        "animals_q02",
        "animals_q03",
        "animals_q04",
        "animals_q05",
        "animals_q06",
        "animals_q07",
        "animals_q08",
        "animals_q09",
        "animals_q10",
        "animals_q11",
        "animals_q12",
        "animals_q13",
        "animals_q14",
        "animals_q15",
        "animals_q16",
        "animals_q17",
        "animals_q18",
    )

    private val countriesWords = listOf(
        TopicWord("countries_egypt", "countries_0"),
        TopicWord("countries_morocco", "countries_0"),
        TopicWord("countries_tunisia", "countries_0"),
        TopicWord("countries_algeria", "countries_0"),
        TopicWord("countries_sudan", "countries_0"),
        TopicWord("countries_france", "countries_1"),
        TopicWord("countries_italy", "countries_1"),
        TopicWord("countries_spain", "countries_1"),
        TopicWord("countries_germany", "countries_1"),
        TopicWord("countries_portugal", "countries_1"),
        TopicWord("countries_japan", "countries_2"),
        TopicWord("countries_china", "countries_2"),
        TopicWord("countries_south_korea", "countries_2"),
        TopicWord("countries_india", "countries_2"),
        TopicWord("countries_thailand", "countries_2"),
        TopicWord("countries_brazil", "countries_3"),
        TopicWord("countries_argentina", "countries_3"),
        TopicWord("countries_mexico", "countries_3"),
        TopicWord("countries_canada", "countries_3"),
        TopicWord("countries_united_states", "countries_3"),
    )

    private val countriesQuestions = listOf(
        "countries_q01",
        "countries_q02",
        "countries_q03",
        "countries_q04",
        "countries_q05",
        "countries_q06",
        "countries_q07",
        "countries_q08",
        "countries_q09",
        "countries_q10",
        "countries_q11",
        "countries_q12",
        "countries_q13",
        "countries_q14",
        "countries_q15",
        "countries_q16",
        "countries_q17",
        "countries_q18",
    )

    private val citiesWords = listOf(
        TopicWord("cities_cairo", "cities_0"),
        TopicWord("cities_alexandria", "cities_0"),
        TopicWord("cities_luxor", "cities_0"),
        TopicWord("cities_aswan", "cities_0"),
        TopicWord("cities_port_said", "cities_0"),
        TopicWord("cities_paris", "cities_1"),
        TopicWord("cities_london", "cities_1"),
        TopicWord("cities_rome", "cities_1"),
        TopicWord("cities_madrid", "cities_1"),
        TopicWord("cities_berlin", "cities_1"),
        TopicWord("cities_tokyo", "cities_2"),
        TopicWord("cities_seoul", "cities_2"),
        TopicWord("cities_beijing", "cities_2"),
        TopicWord("cities_bangkok", "cities_2"),
        TopicWord("cities_singapore", "cities_2"),
        TopicWord("cities_dubai", "cities_3"),
        TopicWord("cities_doha", "cities_3"),
        TopicWord("cities_riyadh", "cities_3"),
        TopicWord("cities_beirut", "cities_3"),
        TopicWord("cities_amman", "cities_3"),
    )

    private val citiesQuestions = listOf(
        "cities_q01",
        "cities_q02",
        "cities_q03",
        "cities_q04",
        "cities_q05",
        "cities_q06",
        "cities_q07",
        "cities_q08",
        "cities_q09",
        "cities_q10",
        "cities_q11",
        "cities_q12",
        "cities_q13",
        "cities_q14",
        "cities_q15",
        "cities_q16",
        "cities_q17",
        "cities_q18",
    )

    private val gamesWords = listOf(
        TopicWord("games_minecraft", "games_0"),
        TopicWord("games_terraria", "games_0"),
        TopicWord("games_stardew_valley", "games_0"),
        TopicWord("games_animal_crossing", "games_0"),
        TopicWord("games_the_sims", "games_0"),
        TopicWord("games_fortnite", "games_1"),
        TopicWord("games_pubg", "games_1"),
        TopicWord("games_valorant", "games_1"),
        TopicWord("games_counter_strike", "games_1"),
        TopicWord("games_overwatch", "games_1"),
        TopicWord("games_chess", "games_2"),
        TopicWord("games_monopoly", "games_2"),
        TopicWord("games_scrabble", "games_2"),
        TopicWord("games_uno", "games_2"),
        TopicWord("games_ludo", "games_2"),
        TopicWord("games_super_mario", "games_3"),
        TopicWord("games_sonic", "games_3"),
        TopicWord("games_crash_bandicoot", "games_3"),
        TopicWord("games_rayman", "games_3"),
        TopicWord("games_donkey_kong", "games_3"),
    )

    private val gamesQuestions = listOf(
        "games_q01",
        "games_q02",
        "games_q03",
        "games_q04",
        "games_q05",
        "games_q06",
        "games_q07",
        "games_q08",
        "games_q09",
        "games_q10",
        "games_q11",
        "games_q12",
        "games_q13",
        "games_q14",
        "games_q15",
        "games_q16",
        "games_q17",
        "games_q18",
    )

    private val technologyWords = listOf(
        TopicWord("technology_smartphone", "technology_0"),
        TopicWord("technology_tablet", "technology_0"),
        TopicWord("technology_laptop", "technology_0"),
        TopicWord("technology_desktop_computer", "technology_0"),
        TopicWord("technology_smartwatch", "technology_0"),
        TopicWord("technology_headphones", "technology_1"),
        TopicWord("technology_speaker", "technology_1"),
        TopicWord("technology_microphone", "technology_1"),
        TopicWord("technology_webcam", "technology_1"),
        TopicWord("technology_projector", "technology_1"),
        TopicWord("technology_keyboard", "technology_2"),
        TopicWord("technology_mouse", "technology_2"),
        TopicWord("technology_game_controller", "technology_2"),
        TopicWord("technology_stylus", "technology_2"),
        TopicWord("technology_touchpad", "technology_2"),
        TopicWord("technology_wi_fi_router", "technology_3"),
        TopicWord("technology_power_bank", "technology_3"),
        TopicWord("technology_usb_drive", "technology_3"),
        TopicWord("technology_external_hard_drive", "technology_3"),
        TopicWord("technology_memory_card", "technology_3"),
    )

    private val technologyQuestions = listOf(
        "technology_q01",
        "technology_q02",
        "technology_q03",
        "technology_q04",
        "technology_q05",
        "technology_q06",
        "technology_q07",
        "technology_q08",
        "technology_q09",
        "technology_q10",
        "technology_q11",
        "technology_q12",
        "technology_q13",
        "technology_q14",
        "technology_q15",
        "technology_q16",
        "technology_q17",
        "technology_q18",
    )

    private val peopleWords = listOf(
        TopicWord("people_adel_emam", "people_0"),
        TopicWord("people_ahmed_helmy", "people_0"),
        TopicWord("people_ahmed_mekky", "people_0"),
        TopicWord("people_mohamed_henedy", "people_0"),
        TopicWord("people_donia_samir_ghanem", "people_0"),
        TopicWord("people_umm_kulthum", "people_1"),
        TopicWord("people_amr_diab", "people_1"),
        TopicWord("people_mohamed_mounir", "people_1"),
        TopicWord("people_sherine", "people_1"),
        TopicWord("people_fairuz", "people_1"),
        TopicWord("people_mohamed_salah", "people_2"),
        TopicWord("people_lionel_messi", "people_2"),
        TopicWord("people_serena_williams", "people_2"),
        TopicWord("people_michael_jordan", "people_2"),
        TopicWord("people_usain_bolt", "people_2"),
        TopicWord("people_albert_einstein", "people_3"),
        TopicWord("people_marie_curie", "people_3"),
        TopicWord("people_ahmed_zewail", "people_3"),
        TopicWord("people_magdi_yacoub", "people_3"),
        TopicWord("people_stephen_hawking", "people_3"),
    )

    private val peopleQuestions = listOf(
        "people_q01",
        "people_q02",
        "people_q03",
        "people_q04",
        "people_q05",
        "people_q06",
        "people_q07",
        "people_q08",
        "people_q09",
        "people_q10",
        "people_q11",
        "people_q12",
        "people_q13",
        "people_q14",
        "people_q15",
        "people_q16",
        "people_q17",
        "people_q18",
    )
}
