package com.parlor.games.whodunit.snapshot

import com.parlor.games.whodunit.domain.phase.WhodunitPhase
import com.parlor.games.whodunit.domain.state.VoteState
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import java.security.MessageDigest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertIs

/**
 * Frozen payloads emitted by the real snapshot codec at checkpoint 8186f7d.
 * The repository adds a conventional final line ending; [legacyBytes] removes
 * only that separator before checking the original generated byte digest.
 */
class WhodunitLegacySnapshotGoldenTest {
    private val codec = WhodunitSnapshotCodec(
        Json {
            encodeDefaults = true
            ignoreUnknownKeys = false
        },
    )

    @Test
    fun checkpoint8186f7dPayloadsRetainTheirGeneratedBytesAndMigrateDeterministically() {
        val setupBytes = legacyBytes(SETUP_FIXTURE)
        val assignedBytes = legacyBytes(ASSIGNED_FIXTURE)
        val tiedBytes = legacyBytes(TIED_FIXTURE)

        assertEquals("68e7603cf9168aee6a5670988aa4a0077eff80fb5988e69b22a84ede81a0eb2b", setupBytes.sha256())
        assertEquals("b0a5230c351be4a35fa3d1ea86feefd3ee54376bd419699821a17bb4562a85a1", assignedBytes.sha256())
        assertEquals("d30908e3b15560969a535a38c41f88829cc126fd9f8056e01411f06042de2a9c", tiedBytes.sha256())

        val setup = codec.decode(setupBytes)
        assertEquals(WhodunitPhase.Setup, setup.phase)
        assertEquals(0L, setup.public.roleAssignmentGeneration)

        val assigned = codec.decode(assignedBytes)
        assertEquals(WhodunitPhase.PublicIntro, assigned.phase)
        assertEquals(1L, assigned.public.roleAssignmentGeneration)
        assertEquals("p3", assigned.hostOnly.killerId.raw)

        val tied = codec.decode(tiedBytes)
        assertEquals(WhodunitPhase.TiedRevote, tied.phase)
        assertEquals(1L, tied.public.roleAssignmentGeneration)
        assertEquals(0, assertIs<VoteState.Tied>(tied.public.voteState).debateSecondsRemaining)
        assertEquals(
            tied.hostOnly.redHerringTargets,
            tied.privatePerPlayer.getValue(tied.hostOnly.killerId).deflectionTargets,
        )

        listOf(setup, assigned, tied).forEach { migrated ->
            val rewritten = codec.encode(migrated)
            val envelope = Json.parseToJsonElement(rewritten.decodeToString()).jsonObject
            assertEquals(WHODUNIT_SNAPSHOT_KIND, envelope.getValue("kind").jsonPrimitive.content)
            assertEquals(
                WHODUNIT_SNAPSHOT_SCHEMA_VERSION.toString(),
                envelope.getValue("schemaVersion").jsonPrimitive.content,
            )
            assertEquals(migrated, codec.decode(rewritten))
        }
    }

    private fun legacyBytes(name: String): ByteArray {
        val stored = requireNotNull(javaClass.getResourceAsStream("/snapshot-goldens/$name")) {
            "Missing snapshot golden $name"
        }.use { it.readBytes() }
        val text = stored.decodeToString().trimEnd('\r', '\n')
        return text.encodeToByteArray()
    }

    private fun ByteArray.sha256(): String = MessageDigest.getInstance("SHA-256")
        .digest(this)
        .joinToString(separator = "") { byte -> "%02x".format(byte) }

    private companion object {
        const val SETUP_FIXTURE = "whodunit-bare-setup-8186f7d.json"
        const val ASSIGNED_FIXTURE = "whodunit-bare-assigned-8186f7d.json"
        const val TIED_FIXTURE = "whodunit-bare-tied-8186f7d.json"
    }
}
