package com.parlor.storage.snapshot

import com.parlor.core.ids.SessionId
import com.parlor.core.result.DataError
import com.parlor.core.result.EmptyOk
import com.parlor.core.result.EmptyResult
import com.parlor.core.result.Result
import com.parlor.engine.snapshot.GameSnapshot
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.serialization.SerializationException
import kotlinx.serialization.json.Json

/**
 * File-backed snapshot store. Persists one JSON file per session under the
 * provided directory.
 *
 * Platform implementations of [SnapshotFileSystem] are responsible for
 * authenticated encryption and OS storage protection before bytes reach disk.
 * Keeping protection below this class also makes atomic replacement and
 * platform key lifecycle one indivisible concern.
 */
class FileBackedSnapshotStore(
    private val fileSystem: SnapshotFileSystem,
    private val json: Json,
) : SnapshotStore {
    private val mutex = Mutex()

    override suspend fun save(snapshot: GameSnapshot): EmptyResult<DataError> = mutex.withLock {
        try {
            val payload = json.encodeToString(GameSnapshot.serializer(), snapshot)
            fileSystem.write(fileName(snapshot.sessionId), payload.encodeToByteArray())
            EmptyOk
        } catch (cancelled: CancellationException) {
            throw cancelled
        } catch (failure: Throwable) {
            Result.Failure(mapToDataError(failure))
        }
    }

    override suspend fun load(sessionId: SessionId): Result<GameSnapshot, DataError> = mutex.withLock {
        try {
            val bytes = fileSystem.read(fileName(sessionId))
                ?: return@withLock Result.Failure(DataError.NotFound)
            Result.Success(json.decodeFromString(GameSnapshot.serializer(), bytes.decodeToString()))
        } catch (cancelled: CancellationException) {
            throw cancelled
        } catch (failure: Throwable) {
            Result.Failure(mapToDataError(failure))
        }
    }

    override suspend fun delete(sessionId: SessionId): EmptyResult<DataError> = mutex.withLock {
        try {
            fileSystem.delete(fileName(sessionId))
            EmptyOk
        } catch (cancelled: CancellationException) {
            throw cancelled
        } catch (failure: Throwable) {
            Result.Failure(mapToDataError(failure))
        }
    }

    override suspend fun listUnfinished(): Result<List<SessionId>, DataError> = mutex.withLock {
        try {
            Result.Success(
                fileSystem.list()
                    .asSequence()
                    .filter(::isSafeSnapshotFileName)
                    .filter { it.endsWith(SUFFIX) }
                    .map { it.removeSuffix(SUFFIX) }
                    .filter { it.isNotBlank() }
                    .distinct()
                    .sorted()
                    .map(::SessionId)
                    .toList(),
            )
        } catch (cancelled: CancellationException) {
            throw cancelled
        } catch (failure: Throwable) {
            Result.Failure(mapToDataError(failure))
        }
    }

    private fun fileName(sessionId: SessionId) = "${sessionId.raw}$SUFFIX"

    private fun mapToDataError(t: Throwable): DataError = when (t) {
        is SerializationException,
        is SnapshotProtectionException -> DataError.CorruptedData
        // Do not copy exception text into a domain error: platform exceptions
        // commonly contain private container paths or key aliases.
        else -> DataError.IoError("snapshot_io")
    }

    companion object {
        const val SUFFIX = ".snapshot.json"
    }
}

/**
 * Platform-agnostic snapshot filesystem contract. Platform `actual`s (Android
 * `Context.filesDir`, iOS `NSDocumentDirectory`, Desktop user-config dir)
 * implement reads/writes against the chosen directory.
 */
interface SnapshotFileSystem {
    suspend fun read(name: String): ByteArray?
    suspend fun write(name: String, bytes: ByteArray)
    suspend fun delete(name: String)
    suspend fun list(): List<String>
}

/**
 * Signals that protected snapshot bytes failed format or authenticity checks.
 * The store maps this to [DataError.CorruptedData] without exposing crypto or
 * filesystem details to the UI.
 */
class SnapshotProtectionException(
    message: String = "snapshot protection failed",
    cause: Throwable? = null,
) : Exception(message, cause)

/**
 * Rejects traversal and temporary-file names at every platform boundary.
 *
 * Session ids are generated by Parlor today, but treating a future restored or
 * network-provided id as a safe path component would be an unnecessary risk.
 */
fun requireSafeSnapshotFileName(name: String) {
    require(isSafeSnapshotFileName(name)) {
        "Invalid snapshot file name"
    }
}

fun isSafeSnapshotFileName(name: String): Boolean =
    name.isNotBlank() &&
        name.length <= MAX_SNAPSHOT_FILE_NAME_LENGTH &&
        name != "." &&
        name != ".." &&
        !name.endsWith(".tmp") &&
        name.none { it == '/' || it == '\\' || it == '\u0000' }

private const val MAX_SNAPSHOT_FILE_NAME_LENGTH = 240
